### PR TITLE
Adds German language Version for site and CoC, see #2

### PR DESCRIPTION
**Pull request by BriocheBerlin**
Before this gets pulled, at least one German native speaker most definitely need(s) to look at this.
I tried to translate rather freely. Not sure it makes sense all the time.

Also: I decided on using the \* (star) version on the gender inklusive language. However this should be open for discussion, some people do prefer _ (underscores) or entirely different ways of writing.
(Though I am vetoing the X version as it is unreadable to people who don't know about it yet.)

Also I didn't know what to do with some of the English terms which found their way into (at least) my use of German. That is mostly true for Git vocabulary but others as well. E.g. I had absolutely no clue on how to deal with "Project Maintainers" which is still in there.

In taking liberties I obviously somewhat changed the text, also in places where it matters.
E.g. "Race" is NOT the same as "Rasse". I chose "Hautfarbe" ("skin color"), because "Rassistische Zuschreibungen" ("racist attributions?" which is as close as you can get in order to describe "Race" in a concise way) isn't easily understandable.
Maybe you have better ideas.

### CODE REVIEW

**Comment by sareg0** [comment]
This is great!! Thank you so much @BriocheBerlin!! 

As both @berlintam and I are not native speakers I am tempted to call on @lislis or @PragTob or maybe @skade, and/or @1000miles for help in this.

**Comment by 1000miles** [comment]
@sareg0 @berlintam @BriocheBerlin 
Hey hey, I am happy to help. Thank you for considering me. I had a sneak preview on your CoC translation. In my opinion it sounds a bit heavy to read and less encouraging for newcomers. If it's okay for you, I would love to improve the text. How much time do I have for this (unless anyone else wants to do this)? :)

**Comment by sareg0** [comment]
It's open ended @1000miles, just as and when :)

**Comment by 1000miles** [comment]
@sareg0 Cool, thank you. :)

**Question:** Is it possible to split the tasks (translation of site & CoC) into 2 different issues (for possible further translations into other languages)?

**Comment by 1000miles** [comment]
@BriocheBerlin @sareg0 @berlintam 
cc @lislis @PragTob @skade

Dear all, so I made the latest commit here:
https://github.com/1000miles/jaa/commit/d26afb2e58444af27c379052a073cd43b798ba1a

**What I have added/improved as suggestions:**
- translated a few english words (for the newcomers whose first language is not always english), hope they are correct though ;)
- used gender neutral terms (this way we don't need to implement \* in all the words)
- added social status, body size
- after consulting with s.o from my networks, I got the recommendation to remove 'identity and expression from gender' because it implies that we are aware of the relevant aspects behind the term 'gender' (which is identity and expression), if we use it (which somehow makes sense to me)
- added race with slashes '/race/' (as @BriocheBerlin already stated that the german word would be problematic because of the Nazi/german colonial history)
- added a link to the original CoC from Contributor Convenant Version

**Not sure about this:**
- I removed "Hautfarbe" bc the term '/race/' would cover this
- I left 'Pull Request', 'Issues' and 'Commits' as I found Github terms hard to translate. Any suggestions?
- changed 'körperlichen Handicaps' to 'Behinderungen' (as this can also mean people who are restricted by their environment) based on these infos [here](http://leidmedien.de/journalistische-tipps/begriffe-von-a-bis-z/) . Any help welcome. :)

**Question:**
- the option to address Sara and Tam via Slack is only possible to those who already have access to the Slack channel, so maybe we can add a hint here?

That's it for now. Happy to discuss with you or explain the content, if required. Let me know what you think. Further improvements welcome. :)

xxx,
Thuy

**Comment by berlintam** [comment]
Thanks so much @1000miles & @BriocheBerlin !!!!

As for your questions: 
- yes, splitting this up into two issues (translation for CoC & of website itself) is a great idea & much easier for one to tackle. 
- yes, you're right, addressing Sara & myself is only possible to those on the slack channel. Perhaps we can change it to say if you're in the channel, slack us, if not, email us. wdyt? I can totally do it today. 

THANKS AGAIN!!

**Comment by 1000miles** [comment]
@berlintam Hi Tam, my pleasure. Alright, I added the Slack info to the CoC DE translation text and will create a pull request now (as favorited by @sareg0), so we all can discuss further on the PR. :)

**Comment by berlintam** [comment]
@BriocheBerlin this is awesome! I love the english/deutsch button! Thanks a kabillion!

Are the other German speakers happy with the *'s? (cc: @1000miles )

If so, Brigitte can you remove your Code of Conduct from this branch? I think that makes sense... because we'll use the one that Thuy made based off of yours.... otherwise there might be conflicts & I don't trust myself to resolve German merge conflicts :scream: Oder? Does that make sense?

**Comment by berlintam** [comment]
Thanks @BriocheBerlin !!!! 
star

**Comment by berlintam** [comment]
(@BriocheBerlin just to clarify, you didn't need to remove your code of conduct because @1000miles  made a branch off your branch, so when I merged hers, yours was automatically changed, that's why I went ahead of the merge. WoooOOoooOt!)

**Pull request merged**
