### PR TITLE
replace info with signup with farewell

### PR DESCRIPTION
**Pull request by sareg0**
comments welcome :)

### CODE REVIEW

**Comment by PragTob** [comment]
:cry: but :+1:

**Comment by berlintam** [comment]
:+1: 
Maybe a final thank you at the bottom & perhaps a gif?

Thanks Sara! I'll deploy this weekend.

**Comment by sareg0** [comment]
okay, I'll get the final touches in this evening

**Comment by berlintam** [comment]
@sareg0 what should we do about the German page?

**Comment by sareg0** [comment]
yes good point. I think it would be nice to have a little goodbye message there too. Perhaps we could do it in a separate PR and @PragTob could help us to make sure it's grammatically correct

**Comment by PragTob** [comment]
Sure thing :+1:

**Pull request merged**
